name: Deploy Hugo PaperMod Demo to Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - main  # 确保与你的实际主分支一致（如果是main，这里改main）
      - exampleSite
  workflow_dispatch:
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.146.0"

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.146.0' }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # 确保与你的代码分支一致
          submodules: false  # 关键：禁用子模块拉取（因为主题已手动提交）

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # 移除子模块相关步骤（因为主题已作为普通文件提交）
      # 原"Get Theme"和"Update theme"步骤删除，避免尝试拉取子模块

      - name: Build with Hugo
        run: |
          hugo \
            --buildDrafts --gc \
            --baseURL ${{ steps.pages.outputs.base_url }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4