name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # 主分支
  workflow_dispatch:  # 允许手动触发

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.151.0  # 与本地版本一致
      SITE_URL: "https://helloworld-myz.github.io/"  # 硬编码你的网站地址
    steps:
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: false  # 若主题是 git 子模块，改为 true

      - name: Clean and set permissions
        run: |
          rm -rf ./blog/public
          chmod -R 755 ./blog

      - name: Build with Hugo（修复 baseURL 参数）
        run: |
          cd ./blog
          # 直接使用硬编码的 SITE_URL，确保 --baseURL 有值
          hugo --baseURL "${{ env.SITE_URL }}"

      - name: Upload blog/public 目录
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./blog/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4